-- add rsa public key
ALTER USER YOUR_SNOWFLAKE_USER SET RSA_PUBLIC_KEY='YOUR_SNOWFLAKE_KEY';

--create database
CREATE OR REPLACE DATABASE LIQUIDRADAR;
CREATE OR REPLACE SCHEMA LIQUIDRADAR.TRADE;

-- create bronze table
CREATE OR REPLACE TABLE LIQUIDRADAR.TRADE.COINBASE_TRADE_BTCUSD_RAW (
    RECORD_METADATA VARIANT,
    RECORD_CONTENT VARIANT
);

-- create silver table
CREATE OR REPLACE TABLE LIQUIDRADAR.TRADE.CRYPTO_TRADE (
    SOURCE VARCHAR(50),
    TICKER VARCHAR(20),
    TRADE_ID VARCHAR(50),
    EVENT_TYPE VARCHAR(50),
    PRICE NUMBER(10, 2),
    SIZE NUMBER(15,8),
    SIDE VARCHAR(4),
    TRADE_TIME_UTC TIMESTAMP_NTZ(9),
    PUBLISH_TIME_UTC TIMESTAMP_NTZ(9),
    CREATE_TIME_UTC TIMESTAMP_NTZ(9)
);

-- create bronze to silver SP
CREATE OR REPLACE PROCEDURE LIQUIDRADAR.TRADE.LOAD_CRYPTO_TRADE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO LIQUIDRADAR.TRADE.CRYPTO_TRADE target --prevent dupes
    USING (
        SELECT
            'Coinbase' AS SOURCE,
            UPPER(SPLIT_PART(RECORD_METADATA:topic::STRING, '.', 3)) AS TICKER,
            RECORD_CONTENT:tradeId::STRING AS TRADE_ID,
            RECORD_CONTENT:eventType::STRING AS EVENT_TYPE,
            RECORD_CONTENT:price::NUMBER(10,2) AS PRICE,
            RECORD_CONTENT:size::NUMBER(15,8) AS SIZE,
            RECORD_CONTENT:side::STRING AS SIDE,
            TO_TIMESTAMP_NTZ(RECORD_CONTENT:time::NUMBER / 1000) AS TRADE_TIME_UTC,
            TO_TIMESTAMP_NTZ(RECORD_METADATA:CreateTime::NUMBER / 1000) AS PUBLISH_TIME_UTC,
            SYSDATE() AS CREATE_TIME_UTC
        FROM LIQUIDRADAR.TRADE.COINBASE_TRADE_BTCUSD_RAW
        WHERE RECORD_CONTENT:tradeId::STRING IS NOT NULL
    ) source
    ON target.TRADE_ID = source.TRADE_ID

    WHEN NOT MATCHED THEN
        INSERT (SOURCE, TICKER, TRADE_ID, EVENT_TYPE, PRICE, SIZE, SIDE, TRADE_TIME_UTC, PUBLISH_TIME_UTC, CREATE_TIME_UTC)
        VALUES (source.SOURCE, source.TICKER, source.TRADE_ID, source.EVENT_TYPE, source.PRICE, source.SIZE, source.SIDE, source.TRADE_TIME_UTC, source.PUBLISH_TIME_UTC, source.CREATE_TIME_UTC);

    RETURN 'Success';
END;
$$;

-- schedule SP task
CREATE OR REPLACE TASK LIQUIDRADAR.TRADE.LOAD_CRYPTO_TRADE_TASK
    SCHEDULE = '1 MINUTE'
    USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AS
    CALL LIQUIDRADAR.TRADE.LOAD_CRYPTO_TRADE();

-- start scheduled task
ALTER TASK LIQUIDRADAR.TRADE.LOAD_CRYPTO_TRADE_TASK RESUME;

-- create gold table for OHLCV data
CREATE OR REPLACE TABLE LIQUIDRADAR.TRADE.CRYPTO_OHLCV (
    TICKER          STRING,
    SOURCE          STRING,
    BUCKET_START    TIMESTAMP_NTZ,
    BUCKET_END      TIMESTAMP_NTZ,
    OPEN            NUMBER(10,2),
    HIGH            NUMBER(10,2),
    LOW             NUMBER(10,2),
    CLOSE           NUMBER(10,2),
    VOLUME          NUMBER(20,8),
    TRADE_COUNT     NUMBER,
    BUY_VOLUME      NUMBER(20,8),
    SELL_VOLUME     NUMBER(20,8),
    CREATE_TIME_UTC TIMESTAMP_NTZ
);

-- create SP for silver -> gold load
CREATE OR REPLACE PROCEDURE LIQUIDRADAR.TRADE.LOAD_CRYPTO_OHLCV(BUCKET_MINUTES NUMBER)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    MERGE INTO LIQUIDRADAR.TRADE.CRYPTO_OHLCV target
    USING (
        WITH ranked AS (
            SELECT
                TICKER,
                SOURCE,
                PRICE,
                SIZE,
                SIDE,
                TRADE_TIME_UTC,
                TIME_SLICE(TRADE_TIME_UTC, :BUCKET_MINUTES, 'MINUTE') AS BUCKET_START,
                DATEADD('MINUTE', :BUCKET_MINUTES, TIME_SLICE(TRADE_TIME_UTC, :BUCKET_MINUTES, 'MINUTE')) AS BUCKET_END,
                FIRST_VALUE(PRICE) OVER (PARTITION BY TICKER, TIME_SLICE(TRADE_TIME_UTC, :BUCKET_MINUTES, 'MINUTE') ORDER BY TRADE_TIME_UTC ASC) AS OPEN,
                LAST_VALUE(PRICE)  OVER (PARTITION BY TICKER, TIME_SLICE(TRADE_TIME_UTC, :BUCKET_MINUTES, 'MINUTE') ORDER BY TRADE_TIME_UTC ASC
                    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS CLOSE
            FROM LIQUIDRADAR.TRADE.CRYPTO_TRADE
            WHERE TRADE_TIME_UTC >= DATEADD('HOUR', -1, SYSDATE())
        )
        SELECT
            TICKER,
            SOURCE,
            BUCKET_START,
            BUCKET_END,
            MAX(OPEN)                                              AS OPEN,
            MAX(PRICE)                                             AS HIGH,
            MIN(PRICE)                                             AS LOW,
            MAX(CLOSE)                                             AS CLOSE,
            SUM(SIZE)                                              AS VOLUME,
            COUNT(*)                                               AS TRADE_COUNT,
            SUM(CASE WHEN SIDE = 'BUY'  THEN SIZE ELSE 0 END)    AS BUY_VOLUME,
            SUM(CASE WHEN SIDE = 'SELL' THEN SIZE ELSE 0 END)     AS SELL_VOLUME,
            SYSDATE()                                              AS CREATE_TIME_UTC
        FROM ranked
        GROUP BY TICKER, SOURCE, BUCKET_START, BUCKET_END
    ) source
    ON target.TICKER = source.TICKER
    AND target.BUCKET_START = source.BUCKET_START
    WHEN MATCHED THEN UPDATE SET
        OPEN            = source.OPEN,
        HIGH            = source.HIGH,
        LOW             = source.LOW,
        CLOSE           = source.CLOSE,
        VOLUME          = source.VOLUME,
        TRADE_COUNT     = source.TRADE_COUNT,
        BUY_VOLUME      = source.BUY_VOLUME,
        SELL_VOLUME     = source.SELL_VOLUME,
        CREATE_TIME_UTC = source.CREATE_TIME_UTC
    WHEN NOT MATCHED THEN INSERT
        (TICKER, SOURCE, BUCKET_START, BUCKET_END, OPEN, HIGH, LOW, CLOSE, VOLUME, TRADE_COUNT, BUY_VOLUME, SELL_VOLUME, CREATE_TIME_UTC)
        VALUES
        (source.TICKER, source.SOURCE, source.BUCKET_START, source.BUCKET_END, source.OPEN, source.HIGH, source.LOW, source.CLOSE, source.VOLUME, source.TRADE_COUNT, source.BUY_VOLUME, source.SELL_VOLUME, source.CREATE_TIME_UTC);

    RETURN 'Success';
END;
$$;

-- suspend silver load task
ALTER TASK LIQUIDRADAR.TRADE.LOAD_CRYPTO_TRADE_TASK SUSPEND;

-- create gold load task chained to silver task
CREATE OR REPLACE TASK LIQUIDRADAR.TRADE.LOAD_CRYPTO_OHLCV_TASK
    AFTER LIQUIDRADAR.TRADE.LOAD_CRYPTO_TRADE_TASK
AS
    CALL LIQUIDRADAR.TRADE.LOAD_CRYPTO_OHLCV(1);  -- 1 min buckets

-- resume silver and gold tasks
ALTER TASK LIQUIDRADAR.TRADE.LOAD_CRYPTO_OHLCV_TASK RESUME;
ALTER TASK LIQUIDRADAR.TRADE.LOAD_CRYPTO_TRADE_TASK RESUME;